apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: team-cluster
  namespace: default
spec:
  teamId: "team"
  volume:
    size: 1Gi
    storageClass: postgres-storageclass
  numberOfInstances: 3
  sidecars:
    - name: "minio"
      image: "vfrans/minio-nas:1.0"
      env:
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          value: "password"
        - name: MINIO_DIR
          value: "/minio"
  additionalVolumes:
    - name: pgbak
      mountPath: /minio
      targetContainers: ["minio"]
      volumeSource:
        hostPath:
          Path: /minio
          Type: Directory


  databases:
    dbtest: usertest

  patroni:
    pg_hba:
      - host all all all md5

  postgresql:
    version: "11"
    parameters:
      shared_buffers: "256MB"
      log_min_duration_statement: "1000"
      log_statement: "ddl"
      log_connections: "on"
      log_disconnections: "on"
      log_checkpoints: "on"
      checkpoint_timeout: "5min"
      max_connections: "500"
      wal_log_hints: "on"
