kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    image: kindest/node:v1.16.15
  - role: worker
    image: kindest/node:v1.16.15
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "persistence_node_id=1"
    extraMounts:
      - hostPath: ~/kind_data/pg
        containerPath: /db
      - hostPath: ~/kind_data/minio
        containerPath: /minio