all:
  hosts:
    node1:
      ansible_host: 52.18.3.176
      ip: 172.31.41.195
      access_ip: 172.31.41.195
      ansible_user: centos
      node_labels:
        persistence_node_id: 1
    node2:
      ansible_host: 34.243.9.250
      ip: 172.31.33.53
      access_ip: 172.31.33.53
      ansible_user: centos
      node_labels:
        persistence_node_id: 2
    node3:
      ansible_host: 54.154.245.53
      ip: 172.31.36.232
      access_ip: 172.31.36.232
      ansible_user: centos
      node_labels:
        persistence_node_id: 3

  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:

    kubespray-nodes:
      hosts:
        node1:
        node2:
        node3:
