all:
  hosts:
    node1:
      ansible_host: 34.240.15.203
      ip: 172.31.34.124
      access_ip: 172.31.34.124
      ansible_user: centos
      node_labels:
        persistence_node_id: 1
    node2:
      ansible_host: 34.243.30.160
      ip: 172.31.33.126
      access_ip: 172.31.33.126
      ansible_user: centos
      node_labels:
        persistence_node_id: 2
    node3:
      ansible_host: 3.251.65.46
      ip: 172.31.45.2
      access_ip: 172.31.45.2
      ansible_user: centos
      node_labels:
        persistence_node_id: 3

  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:

    kubespray-nodes:
      hosts:
        node1:
        node2:
        node3:
