apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-var-custom
data:
  BACKUP_SCHEDULE: "0 */12 * * *"
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  BACKUP_NUM_TO_RETAIN: "14"
  AWS_ACCESS_KEY_ID: "admin"
  AWS_SECRET_ACCESS_KEY: "password"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT: "http://minio:9000"
  AWS_S3_FORCE_PATH_STYLE: "true"
  WALG_S3_PREFIX: "s3://testbucket"
