apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9000
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio

  template:
    metadata:
      labels:
        app: minio
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: spilo-role
                    operator: In
                    values:
                      - master
              topologyKey: "kubernetes.io/hostname"
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              value: "admin"
            - name: MINIO_SECRET_KEY
              value: "password"
          image: minio/minio:RELEASE.2020-11-25T22-36-25Z
          command: ['minio', 'server', '/minio']
          imagePullPolicy: "IfNotPresent"
          name: minio
          volumeMounts:
            - mountPath: /minio
              name: miniodisk
              mountPropagation: HostToContainer
      restartPolicy: Always
      volumes:
        - name: miniodisk
          hostPath:
            path: /minio
            type: Directory
