apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storageclass
  local:
    path: /db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key:  kubernetes.io/hostname
              operator: In
              values:
                - "node1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv2
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storageclass
  local:
    path: /db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key:  kubernetes.io/hostname
              operator: In
              values:
                - "node2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv3
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-storageclass
  local:
    path: /db
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key:  kubernetes.io/hostname
              operator: In
              values:
                - "node3"